### ISSUE TITLE
Build Issues

### ISSUE THREAD

**Issue by part1cleth1ef** [OperatorFoundation/Amber#1]
when building using Amber, these errors come up.
<img width="681" alt="image" src="https://github.com/OperatorFoundation/Amber/assets/70655838/96b10ba7-fa13-4328-a2e9-c3a7f443ee55">
Here is the code editor on the file which has the errors.
<img width="1439" alt="image" src="https://github.com/OperatorFoundation/Amber/assets/70655838/e7f89ce4-f7d0-484d-93a9-95df499421ea">
Thanks!

**Comment by blanu** [comment]
Thank you for the bug report. I think that this is because you are compiling for iOS and we previously have only compiled for macOS. It seems that Foundation for macOS includes AffineTransform and Foundation for iOS does not. We are now going through and removing all Foundation classes that are only on macOS so that iOS compilation will work. So hopefully we will have a commit soon fixing iOS compilation.
